const deals=[
{id:1,title:'삼성 990 PRO NVMe 2TB',price:189000,shop:'쿠팡',source:'뽐뿌',cat:'PC',rating:'역대가',low:189000,avg:216000,time:'3분 전',watch:true},
{id:2,title:'로지텍 G PRO X SUPERLIGHT 2',price:129000,shop:'11번가',source:'퀘이사존',cat:'PC',rating:'핫딜',low:119000,avg:149000,time:'8분 전',watch:false},
{id:3,title:'PlayStation 5 듀얼센스',price:59800,shop:'네이버',source:'루리웹',cat:'게임',rating:'역대가 근접',low:59000,avg:69000,time:'12분 전',watch:false},
{id:4,title:'Apple AirPods Pro 2 USB-C',price:279000,shop:'G마켓',source:'뽐뿌',cat:'모바일',rating:'좋은 가격',low:259000,avg:292000,time:'19분 전',watch:true},
{id:5,title:'햇반 210g 36개',price:32900,shop:'옥션',source:'FM코리아',cat:'식품',rating:'핫딜',low:30900,avg:38900,time:'25분 전',watch:false},
{id:6,title:'다이슨 무선청소기 V12',price:489000,shop:'SSG',source:'뽐뿌',cat:'생활',rating:'좋은 가격',low:459000,avg:515000,time:'31분 전',watch:false}
];
let cat='';const $=s=>document.querySelector(s);const money=n=>n.toLocaleString('ko-KR')+'원';
function badge(r){return r==='역대가'?'record':r==='역대가 근접'?'near':r==='핫딜'?'hot':'good'}
function render(){const q=$('#search').value.toLowerCase(),src=$('#source').value,rat=$('#rating').value;const rows=deals.filter(d=>(!q||(d.title+' '+d.shop).toLowerCase().includes(q))&&(!src||d.source===src)&&(!rat||d.rating===rat)&&(!cat||d.cat===cat));$('#deals').innerHTML=rows.map(d=>`<article class="deal"><div><div class="top"><span class="badge ${badge(d.rating)}">${d.rating==='역대가'?'🔥 ':d.rating==='핫딜'?'🟢 ':d.rating==='역대가 근접'?'🟠 ':'🟡 '}${d.rating}</span><span class="badge">${d.source}</span><span class="badge">${d.cat}</span></div><h2>${d.title}</h2><div class="price">${money(d.price)}</div><div class="meta">${d.shop} · ${d.time}</div><div class="history">관측 최저 ${money(d.low)} · 관측 평균 ${money(d.avg)}</div></div><div class="right"><div class="delta">평균 대비 ${Math.round((d.price/d.avg-1)*100)}%</div><div class="meta">최저가 대비 +${((d.price/d.low-1)*100).toFixed(1)}%</div><a class="link" href="#" onclick="alert('DEMO에서는 원문 링크가 연결되지 않습니다.');return false">원문 보기 →</a></div></article>`).join('')||'<div class="notice">조건에 맞는 딜이 없습니다.</div>'}
$('#count').textContent=deals.length;$('#recordCount').textContent=deals.filter(d=>d.rating==='역대가').length;$('#watchCount').textContent=deals.filter(d=>d.watch).length;['search','source','rating'].forEach(id=>$('#'+id).addEventListener('input',render));document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;render()});render();
